<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentLeitorHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['marca'])) {
            $value = $data['marca'];
            $return = (string) $value;
            $this->class->reflFields['marca']->setValue($document, $return);
            $hydratedData['marca'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['modelo'])) {
            $value = $data['modelo'];
            $return = (string) $value;
            $this->class->reflFields['modelo']->setValue($document, $return);
            $hydratedData['modelo'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['serie'])) {
            $value = $data['serie'];
            $return = (string) $value;
            $this->class->reflFields['serie']->setValue($document, $return);
            $hydratedData['serie'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['usado'])) {
            $value = $data['usado'];
            $return = (bool) $value;
            $this->class->reflFields['usado']->setValue($document, $return);
            $hydratedData['usado'] = $return;
        }
        return $hydratedData;
    }
}