<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentPontoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['lat'])) {
            $value = $data['lat'];
            $return = (string) $value;
            $this->class->reflFields['lat']->setValue($document, $return);
            $hydratedData['lat'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['lng'])) {
            $value = $data['lng'];
            $return = (string) $value;
            $this->class->reflFields['lng']->setValue($document, $return);
            $hydratedData['lng'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['numero'])) {
            $value = $data['numero'];
            $return = (string) $value;
            $this->class->reflFields['numero']->setValue($document, $return);
            $hydratedData['numero'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['endereco'])) {
            $value = $data['endereco'];
            $return = (string) $value;
            $this->class->reflFields['endereco']->setValue($document, $return);
            $hydratedData['endereco'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['leitor'])) {
            $reference = $data['leitor'];
            if (isset($this->class->fieldMappings['leitor']['simple']) && $this->class->fieldMappings['leitor']['simple']) {
                $className = $this->class->fieldMappings['leitor']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['leitor'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['leitor']->setValue($document, $return);
            $hydratedData['leitor'] = $return;
        }
        return $hydratedData;
    }
}