<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <!--<div class="user-panel">
            <div class="pull-left image">
                <img src="../../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>-
            <div class="pull-left info">
                <p>Joabe Pinheiro</p>
                <a href="#">Contador</a>
            </div>
        </div>->
        <!-- search form -->
        <!-- <form action="#" method="get" class="sidebar-form">
             <div class="input-group">
                 <input type="text" name="q" class="form-control" placeholder="Search...">
               <span class="input-group-btn">
                 <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
               </span>
             </div>
         </form>-->
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <!-- <li class="header">MAIN NAVIGATION</li>-->

            <li class="treeview">
                <a href="<?php echo $this->url('onibus/default', array('action' => 'listar'))?>">
                    <i class="fa fa-bus"></i> <span>Onibus</span>
                </a>
            </li>

            <li class="treeview">
                <a href="<?php echo $this->url('usuario/default', array('action' => 'listar'))?>">
                    <i class="fa fa-user"></i> <span>Usuario</span>
                </a>
            </li>
            <li class="treeview">
                <a href="<?php echo $this->url('leitor/default', array('action' => 'listar'))?>">
                    <i class="fa fa-eye"></i> <span>Leitor</span>
                </a>
            </li>
            <li class="treeview">
                <a href="<?php echo $this->url('etiqueta/default', array('action' => 'listar'))?>">
                    <i class="fa fa-tag"></i> <span>Etiqueta</span>
                </a>
            </li>
            <li class="treeview">
                <a href="<?php echo $this->url('ponto/default', array('action' => 'listar'))?>">
                    <i class="fa fa-tag"></i> <span>Ponto</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>