<?php

namespace Application\Service;

use Doctrine\ODM\MongoDB\DocumentManager;

class Itinerario extends AbstractService{

    public function __construct(DocumentManager $dm){
        parent::__construct($dm);
        $this->entity = 'Application\Document\Itinerario';
    }

    public function insert($data)
    {
        $data['linha'] = $this->documentManager->getRepository('Application\Document\Linha')->find($data['linha']);
        $data['ponto'] = $this->documentManager->getRepository('Application\Document\Ponto')->find($data['ponto']);


        return parent::insert($data); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        $data['linha'] = $this->documentManager->getRepository('Application\Document\Linha')->find($data['linha']);
        $data['ponto'] = $this->documentManager->getRepository('Application\Document\Ponto')->find($data['ponto']);
        
        return parent::update($data); // TODO: Change the autogenerated stub
    }
}
