<?php

namespace Application\Service;

use Doctrine\ODM\MongoDB\DocumentManager;
use Zend\Hydrator\ClassMethods;

class Log extends AbstractService{

    public function __construct(DocumentManager $dm){
        parent::__construct($dm);
        $this->entity = 'Application\Document\Log';
    }

    public function update($data)
    {
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    
}
