<?php

namespace Application\Service;

use Doctrine\ODM\MongoDB\DocumentManager;

class Ponto extends AbstractService{

    public function __construct(DocumentManager $dm){
        parent::__construct($dm);
        $this->entity = 'Application\Document\Ponto';
    }

    public function insert($data)
    {

        if(!empty($data['leitor'])){

            $data['leitor'] = $this->documentManager->getRepository('Application\Document\Leitor')->find($data['leitor']);
            $data['leitor']->setUsado(1);
            (new Leitor($this->documentManager))->update($data['leitor']->toArray());
        }else{
            unset($data['leitor']);
        }


        return parent::insert($data); // TODO: Change the autogenerated stub
    }
    
    public function delete($id)
    {
        $entity = $this->documentManager->getRepository($this->entity)->find($id);
        $leitor = $entity->getLeitor();

        if(is_null(!$leitor)){
            $leitor->setUsado(false);
            (new Leitor($this->documentManager))->update($leitor->toArray());
        }

        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
